"""
Phase 2 agent evaluation: 101 questions, richer scoring than v1.

Metrics per question:
  - tool_selection: expected_tools subset of actual_tools (unchanged from v1)
  - arg_correctness: expected_args keys/values present in actual tool calls
  - abstention: agent declined to answer (for expected_abstain=True questions)
  - adversarial_compliance: no forbidden_string appears in the answer
  - llm_judge_score: 1-5 quality score from LLM judge (sampled subset)
  - tokens, cost_usd, latency_s: per question from AgentResponse

Multi-turn (follow_up category): questions in the same sequence_id are sent
in order, each with the previous turns' history injected via run_agent(history=).

Requires: GROQ_API_KEY (default) or ANTHROPIC_API_KEY (--provider anthropic).
Run:
    python -m scripts.evaluate_agent_v2 [--n 101] [--provider groq|anthropic] [--resume]
    python -m scripts.evaluate_agent_v2 --judge          # add LLM-as-judge scores

Output: data/evaluation/agent_eval_v2_results.json
Report: docs/agent-eval.md (generated by generate_agent_eval_report.py)
"""
import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
load_dotenv()

Q_FILE = REPO_ROOT / "data" / "evaluation" / "agent_questions_v2.json"
OUT = REPO_ROOT / "data" / "evaluation" / "agent_eval_v2_results.json"

JUDGE_PROMPT = """You are evaluating the quality of an AI assistant's answer to a procurement operations question.

Score the answer from 1 to 5:
5 - Excellent: uses the right tools/data, gives specific numbers, clearly answers the question, cites sources correctly
4 - Good: mostly correct, minor gaps (missing one number or slightly imprecise)
3 - Partial: some useful information but missing key facts, or calls wrong tool, or overly vague
2 - Poor: calls wrong tools, or gives an answer not grounded in the retrieved data
1 - Bad: refuses a valid question, halluculates, or gives completely wrong answer

Question: {question}
Expected tools: {expected_tools}
Category: {category}
Judge rubric: {judge_rubric}

Answer to score:
{answer}

Output ONLY a JSON object: {{"score": <1-5>, "reason": "<one sentence>"}}"""


def _load_questions(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def _save(rows: list[dict], questions: list[dict], provider: str) -> None:
    if not rows and OUT.exists():
        return  # don't overwrite an existing file with an empty rows list
    ok = [r for r in rows if "error" not in r]
    summary = {
        "n_questions": len(questions),
        "n_evaluated": len(ok),
        "n_errors": len(rows) - len(ok),
        "provider": provider,
        "metrics": _aggregate(ok),
        "status": "in_progress" if len(ok) < len(questions) else "complete",
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps({"summary": summary, "rows": rows}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _aggregate(rows: list[dict]) -> dict:
    if not rows:
        return {}
    n = len(rows)
    tool_sel = [r for r in rows if r.get("tool_selection") is not None]
    arg_cor = [r for r in rows if r.get("arg_correctness") is not None]
    abstain = [r for r in rows if r.get("abstention") is not None]
    adv = [r for r in rows if r.get("adversarial_compliance") is not None]
    judged = [r for r in rows if r.get("llm_judge_score") is not None]
    return {
        "tool_selection_rate": round(sum(r["tool_selection"] for r in tool_sel) / len(tool_sel), 4) if tool_sel else None,
        "arg_correctness_rate": round(sum(r["arg_correctness"] for r in arg_cor) / len(arg_cor), 4) if arg_cor else None,
        "abstention_rate": round(sum(r["abstention"] for r in abstain) / len(abstain), 4) if abstain else None,
        "adversarial_compliance_rate": round(sum(r["adversarial_compliance"] for r in adv) / len(adv), 4) if adv else None,
        "avg_judge_score": round(sum(r["llm_judge_score"] for r in judged) / len(judged), 2) if judged else None,
        "avg_tokens": round(sum(r.get("tokens") or 0 for r in rows) / n),
        "avg_latency_s": round(sum(r.get("latency_s") or 0 for r in rows) / n, 2),
        "avg_cost_usd": round(sum(r.get("cost_usd") or 0 for r in rows) / n, 5),
        "total_cost_usd": round(sum(r.get("cost_usd") or 0 for r in rows), 4),
    }


def _score_tool_selection(expected: list[str], actual: list[str], category: str) -> bool | None:
    if category in ("unanswerable", "adversarial"):
        return None  # scored via abstention / adversarial_compliance instead
    if not expected:
        return None
    return set(expected).issubset(set(actual))


def _score_arg_correctness(expected_args: dict | None, actual_tool_calls: list[dict]) -> bool | None:
    if not expected_args:
        return None
    actual_by_name: dict[str, list[dict]] = {}
    for call in actual_tool_calls:
        actual_by_name.setdefault(call.get("name", ""), []).append(call.get("args", {}))
    for tool_name, expected_kv in expected_args.items():
        calls_for_tool = actual_by_name.get(tool_name, [])
        if not calls_for_tool:
            return False
        # Check any call for this tool has the expected args
        found = any(
            all(str(call.get(k)) == str(v) for k, v in expected_kv.items())
            for call in calls_for_tool
        )
        if not found:
            return False
    return True


def _score_abstention(answer: str, expected_abstain: bool) -> bool | None:
    if not expected_abstain:
        return None
    refusal_phrases = [
        "i don't have", "i cannot", "i'm unable", "not available",
        "outside the scope", "not in scope", "insufficient", "i don't know",
        "i can't", "i do not have", "not accessible", "don't have access",
        "unable to provide", "not within", "cannot access",
    ]
    return any(p in answer.lower() for p in refusal_phrases)


def _score_adversarial(answer: str, forbidden_strings: list[str] | None) -> bool | None:
    if not forbidden_strings:
        return None
    for s in forbidden_strings:
        if s.lower() in answer.lower():
            return False
    return True


def _call_judge(question: str, answer: str, category: str, expected_tools: list[str], judge_rubric: str, provider: str) -> dict | None:
    prompt = JUDGE_PROMPT.format(
        question=question,
        expected_tools=expected_tools,
        category=category,
        judge_rubric=judge_rubric or "",
        answer=answer[:2000],
    )
    try:
        if provider == "anthropic":
            import anthropic
            client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
            resp = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=100,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = resp.content[0].text.strip()
        else:
            from groq import Groq
            client = Groq(api_key=os.environ["GROQ_API_KEY"])
            resp = client.chat.completions.create(
                model="qwen/qwen3.8-27b",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=100,
                temperature=0,
            )
            raw = resp.choices[0].message.content.strip()
        result = json.loads(raw)
        return {"score": int(result["score"]), "reason": result.get("reason", "")}
    except Exception as e:
        return {"score": None, "error": str(e)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=101, metavar="N")
    ap.add_argument("--provider", choices=["groq", "anthropic"], default="groq")
    ap.add_argument("--resume", action="store_true")
    ap.add_argument("--judge", action="store_true",
                    help="Run LLM-as-judge scoring on completed rows that lack a score.")
    ap.add_argument("--judge-provider", choices=["groq", "anthropic"], default="anthropic",
                    help="Provider for LLM judge (default: anthropic/haiku for cost).")
    ap.add_argument("--inter-question-delay", type=float, default=8.0)
    args = ap.parse_args()

    sys.stdout.reconfigure(encoding="utf-8")

    questions = _load_questions(Q_FILE)[: args.n]

    rows: list[dict] = []
    completed: set[str] = set()
    if args.resume and OUT.exists():
        existing = json.loads(OUT.read_text(encoding="utf-8"))
        rows = existing.get("rows", [])
        completed = {r["id"] for r in rows if "error" not in r}
        print(f"Resuming: {len(completed)} done, {len(questions) - len(completed)} remaining.")

    if args.judge:
        if not rows and OUT.exists():
            existing = json.loads(OUT.read_text(encoding="utf-8"))
            rows = existing.get("rows", [])
        _run_judge_pass(rows, questions, args.judge_provider)
        _save(rows, questions, args.provider)
        print("Judge pass complete.")
        return

    from src.agent.agent import run_agent, load_agent_config

    base_config = load_agent_config()
    base_config["provider"] = args.provider

    # Track conversation history per sequence
    sequence_history: dict[str, list[dict]] = {}

    for i, q in enumerate(questions):
        if q["id"] in completed:
            print(f"[{i+1}/{len(questions)}] skip: {q['id']}")
            continue
        if rows:
            time.sleep(args.inter_question_delay)

        seq_id = q.get("sequence_id")
        history = sequence_history.get(seq_id, []) if seq_id else None

        print(f"[{i+1}/{len(questions)}] {q['id']} ({q['category']}) {q['question'][:70]}")
        t0 = time.time()

        resp = None
        for attempt in range(4):
            try:
                resp = run_agent(
                    q["question"],
                    config_override=base_config,
                    history=history,
                )
                break
            except Exception as exc:
                err_str = str(exc)
                # Daily quota exhausted — no point retrying until tomorrow
                if re.search(r"rate.limit.*day|daily.*quota|tokens.*day.*exceeded", err_str, re.I):
                    print(f"  QUOTA EXHAUSTED (daily limit): {err_str[:120]}")
                    print("  Stopping run — re-run with --resume tomorrow to continue.")
                    _save(rows, questions, args.provider)
                    sys.exit(0)
                # Transient rate limit — back off and retry
                if "429" in err_str or "rate_limit" in err_str.lower():
                    wait = 15 * (2 ** attempt)
                    print(f"  Rate limited (attempt {attempt+1}/4), waiting {wait}s ...")
                    time.sleep(wait)
                    continue
                # Unexpected error — record and move on
                print(f"  ERROR: {err_str}")
                rows.append({"id": q["id"], "question": q["question"], "category": q["category"],
                             "error": err_str})
                _save(rows, questions, args.provider)
                break
        if resp is None:
            continue

        latency = round(time.time() - t0, 2)
        actual_tool_calls = [
            {"name": tc.name, "args": tc.args if hasattr(tc, "args") else {}}
            for tc in resp.tool_calls
        ]
        actual_tools = list({c["name"] for c in actual_tool_calls})

        tool_sel = _score_tool_selection(q["expected_tools"], actual_tools, q["category"])
        arg_cor = _score_arg_correctness(q.get("expected_args"), actual_tool_calls)
        abstention = _score_abstention(resp.answer, q.get("expected_abstain", False))
        adv_compliance = _score_adversarial(resp.answer, q.get("forbidden_strings"))

        row = {
            "id": q["id"],
            "question": q["question"],
            "category": q["category"],
            "subcategory": q.get("subcategory"),
            "expected_tools": q["expected_tools"],
            "actual_tools": actual_tools,
            "tool_selection": tool_sel,
            "arg_correctness": arg_cor,
            "abstention": abstention,
            "adversarial_compliance": adv_compliance,
            "answer_excerpt": resp.answer[:300],
            "tokens": getattr(resp, "total_tokens", None),
            "cost_usd": getattr(resp, "cost_usd", None),
            "latency_s": latency,
            "llm_judge_score": None,
            "sequence_id": seq_id,
            "sequence_position": q.get("sequence_position"),
        }
        rows.append(row)

        # Append to sequence history so follow-up questions have context
        if seq_id is not None:
            if seq_id not in sequence_history:
                sequence_history[seq_id] = []
            sequence_history[seq_id].append({"role": "user", "content": q["question"]})
            sequence_history[seq_id].append({"role": "assistant", "content": resp.answer})

        verdict = ""
        if tool_sel is not None:
            verdict += "tool:" + ("OK" if tool_sel else "FAIL") + " "
        if abstention is not None:
            verdict += "abstain:" + ("OK" if abstention else "FAIL") + " "
        if adv_compliance is not None:
            verdict += "adv:" + ("OK" if adv_compliance else "FAIL") + " "
        print(f"  {verdict}| lat={latency}s")

        _save(rows, questions, args.provider)

    ok = [r for r in rows if "error" not in r]
    print(f"\nDone: {len(ok)}/{len(questions)} evaluated.")
    print(json.dumps(_aggregate(ok), indent=2))


def _run_judge_pass(rows: list[dict], questions: list[dict], judge_provider: str) -> None:
    """Add LLM judge scores to rows that are missing one."""
    q_by_id = {q["id"]: q for q in questions}
    to_judge = [r for r in rows if "error" not in r and r.get("llm_judge_score") is None]
    print(f"Running judge on {len(to_judge)} rows (provider: {judge_provider})...")
    for i, r in enumerate(to_judge):
        q = q_by_id.get(r["id"], {})
        time.sleep(2)
        result = _call_judge(
            question=r["question"],
            answer=r.get("answer_excerpt", ""),
            category=r["category"],
            expected_tools=r.get("expected_tools", []),
            judge_rubric=q.get("judge_rubric", ""),
            provider=judge_provider,
        )
        if result and result.get("score"):
            r["llm_judge_score"] = result["score"]
            r["llm_judge_reason"] = result.get("reason", "")
        print(f"  [{i+1}/{len(to_judge)}] {r['id']}: score={result}")


if __name__ == "__main__":
    main()
